import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/navigation/navbar";
import {auth} from '@/lib/auth';
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sprout Scribble",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });
  console.log('SESSION: ', session)



  return (
    <html lang="en">
      <body
        className={cn(
          "px-6 md:px-12 max-w-7xl mx-auto",
          `${geistSans.variable} ${geistMono.variable} antialiased`
        )}
      >
        <Navbar session={session}/>
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
